// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Citizens, CitizensData, CitizensTableId } from "./tables/Citizens.sol";
import { Proposal, ProposalData, ProposalTableId } from "./tables/Proposal.sol";
import { Cities, CitiesData, CitiesTableId } from "./tables/Cities.sol";
