// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Citizens, CitizensData, CitizensTableId } from "./tables/Citizens.sol";
import { CitizensCounter, CitizensCounterTableId } from "./tables/CitizensCounter.sol";
import { Proposals, ProposalsData, ProposalsTableId } from "./tables/Proposals.sol";
import { ProposalCounter, ProposalCounterTableId } from "./tables/ProposalCounter.sol";
import { CitiesCounter, CitiesCounterTableId } from "./tables/CitiesCounter.sol";
import { Voting, VotingTableId } from "./tables/Voting.sol";
import { Cities, CitiesData, CitiesTableId } from "./tables/Cities.sol";
import { VerifiedCities, VerifiedCitiesTableId } from "./tables/VerifiedCities.sol";
import { SupercitiesTokenTable, SupercitiesTokenTableTableId } from "./tables/SupercitiesTokenTable.sol";
