// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICitizenSystem {
  error InvalidCitizen();
  error CitizenAlreadyExists();
  error CityAlreadyVerified();
  error CannotCommitToCity();
  error CannotClaimReward();

  function addCitizen(
    address _citizenId,
    string memory _name,
    uint256 _verifiedCities,
    string memory _roleAttestation,
    uint256 _level,
    uint256 _gamePoints,
    uint256 _cityCommittedTo
  ) external;

  function verifyCity(address _citizenId, uint256 _cityId) external;

  function commitToCity(address _citizenId, uint256 _cityId) external;

  function claimReward(address _citizenId) external;
}
