// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICitiesSystem {
  error UnregisteredCitizen();
  error AlreadyVoted();
  error ExpiredVotingPeriod();

  function proposeCity(address _citizen, string memory _city, string memory _country) external;

  function upvote(uint256 _proposalId) external;

  function downvote(uint256 _proposalId) external;

  function addCity() external;
}
