// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISupercitiesSystem {
  function retrieveName() external returns (string memory name);

  function mintTokens(address _citizen, uint256 _amount) external;

  function setAddress(address _scAddress) external;

  function retrieveAddress() external returns (address);
}
